# Generated by Django 6.0.5 on 2026-05-17 05:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.IntegerField(unique=True, verbose_name='회차')),
                ('draw_date', models.DateTimeField(blank=True, null=True, verbose_name='추첨일')),
                ('n1', models.IntegerField(blank=True, null=True)),
                ('n2', models.IntegerField(blank=True, null=True)),
                ('n3', models.IntegerField(blank=True, null=True)),
                ('n4', models.IntegerField(blank=True, null=True)),
                ('n5', models.IntegerField(blank=True, null=True)),
                ('n6', models.IntegerField(blank=True, null=True)),
                ('bonus', models.IntegerField(blank=True, null=True, verbose_name='보너스')),
                ('is_drawn', models.BooleanField(default=False, verbose_name='추첨완료')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='회차 생성일')),
            ],
            options={
                'ordering': ['-round_no'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n1', models.IntegerField()),
                ('n2', models.IntegerField()),
                ('n3', models.IntegerField()),
                ('n4', models.IntegerField()),
                ('n5', models.IntegerField()),
                ('n6', models.IntegerField()),
                ('pick_type', models.CharField(choices=[('M', '수동'), ('A', '자동')], max_length=1, verbose_name='구매방식')),
                ('price', models.IntegerField(default=1000, verbose_name='금액')),
                ('purchased_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='구매일시')),
                ('rank', models.IntegerField(default=0, verbose_name='당첨순위')),
                ('prize', models.IntegerField(default=0, verbose_name='당첨금')),
                ('draw_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='lotto.drawround', verbose_name='회차')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='구매자')),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
    ]
